### ISSUE TITLE
difference between cross and same domain 

### ISSUE THREAD

**Issue by Laidawang** [Shilin-LU/TF-ICON#12]
I want to know what the difference is. Is it just a difference in scale? What impact will it have from an intuitive perspective? I don't seem to find this element in the paper.

**Comment by Shilin-LU** [comment]
Hi, thank you for your question.

This brief discussion can be found in the final paragraph of Section 4.2, under "Noise incorporation." 

They are mainly different in the composition space of noise, which is an empirical choice.
