### ISSUE TITLE
Foreground mask

### ISSUE THREAD

**Issue by Orange-rightperson** [Shilin-LU/TF-ICON#13]
I notice the code need Foreground mask, but never mentioned in the paper, would you please tell me the reason?

**Comment by Shilin-LU** [comment]
Kindly read `Section B.1 Preprocessing` of our paper. Thank you.

**Comment by Orange-rightperson** [comment]
@Shilin-LU Sorry for that, thanks for you reply

**Comment by Shilin-LU** [comment]
@Orange-rightperson  Also `Section 5.2 Test benchmark`, `Figure 11`, $\mathbf{M}^\text{seg}$ in `Equation 5`, `Algorithm 1`.

> I notice the code need Foreground mask, but never mentioned in the paper, would you please tell me the reason?

**Comment by Orange-rightperson** [comment]
@Shilin-LU  Thanks for your reply
