### ISSUE TITLE
So we must wait until the foreground image needs to be placed at the appropriate location, and the model cannot calculate the suitable location by itself, right

### ISSUE THREAD

**Issue by sjz-hub** [Shilin-LU/TF-ICON#14]
So we must wait until the foreground image needs to be placed at the appropriate location, and the model cannot calculate the suitable location by itself, right？

**Comment by Shilin-LU** [comment]
Yes, you raise an interesting aspect. Usually, an appropriate location that harmoniously aligns with the background context can integrate the foreground into the background effectively. 

However, when the location is unsuitable, the composition becomes 'sensitive' or 'unstable'. Training the model to identify optimal locations for composition could indeed be a fascinating thing.
