### ISSUE TITLE
Can I merge a 30 * 30 pixel foreground image into a 720 * 1280 background image

### ISSUE THREAD

**Issue by sjz-hub** [Shilin-LU/TF-ICON#15]
Can I merge a 30 * 30 pixel foreground image into a 720 * 1280 background image？

**Comment by Shilin-LU** [comment]
The 30*30 foreground may be too small. Our method may not be able to handle small object compositions.

**Comment by Shilin-LU** [comment]
30x30 may be okay, but 720x1280 is not the resolution that can be handled by SD v1 & v2. You may need to resize or crop to 512x512, or look for other base models like SDXL. But we haven't implemented our method on it.

**Comment by sjz-hub** [comment]
Thanks!Can you recommend some fusion of small target foreground objects? I am interested in this area.

**Comment by sjz-hub** [comment]
Thank you very much. I will try to merge the foreground image of 30 * 30 into 512 * 512 and see how the effect works

**Comment by Shilin-LU** [comment]
No problem :) 
You can also check the paper 'paint by example: exemplar-based image editing with diffusion models' to see if it is helpful for you.
