### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by Lifedecoder** [Shilin-LU/TF-ICON#16]
When running main.py as instructed, a quite weird error occurs at
https://github.com/Shilin-LU/TF-ICON/blob/d4271927c0afc56da70be736bed11ac45af13fa3/scripts/main_tf_icon.py#L79

The error tells like:

> TypeError: get_learned_conditioning() takes 2 positional arguments but 3 were given

the function 'get_learned_conditioning' in ddpm obviously takes in two argument, here prompts is ['a pencil drawing of an eiffel tower in the distance, black and white painting'] and inv = True, i can't see anywhere wrong.
Might it caused by the version of stable diffusion (like function might change in different models)?i used the same pretrained stable diffusion as link refers to.

**Comment by Lifedecoder** [comment]
It seems like it is, i find in the newest version of stable diffusion, the option 'inv' is removed:
https://github.com/Stability-AI/stablediffusion/blob/cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf/ldm/models/diffusion/ddpm.py#L662

as in this repo, inv is still applied:
https://github.com/Shilin-LU/TF-ICON/blob/d4271927c0afc56da70be736bed11ac45af13fa3/ldm/models/diffusion/ddpm.py#L662

**Comment by Shilin-LU** [comment]
Ya, you're right. Better to keep the same version as ours and use our source code to avoid this type of error.

**Comment by Lifedecoder** [comment]
Which version did you use? i tried the same checkpoint from designated link: [Stability AI at Hugging Face](https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/v2-1_512-ema-pruned.ckpt), still failed, seems your link points to lastest version.

**Comment by Shilin-LU** [comment]
> Which version did you use? i tried the same checkpoint from designated link: [Stability AI at Hugging Face](https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/v2-1_512-ema-pruned.ckpt), still failed, seems your link points to lastest version.

Hi, I recommend that you adhere to our guidelines for creating the conda environment to ensure you have the correct versions, particularly of the `diffusers` and `transformers` versions. It would be beneficial to remove your existing environment for tf-icon and establish a new one by following the steps outlined below.

```
git clone https://github.com/Shilin-LU/TF-ICON.git
cd TF-ICON
conda env create -f tf_icon_env.yaml
conda activate tf-icon
```

**Comment by Lifedecoder** [comment]
ok, thanks for your quick response!
