### ISSUE TITLE
Questions Regrading the Implementation

### ISSUE THREAD

**Issue by Yutong-Dai** [Shilin-LU/TF-ICON#17]
Hi, thanks for releasing the code. It's very interesting work. 
I am new to this topic. Therefore, I have several questions regarding the code that I hope you can help address.

1. In the [`attention.py` file](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/modules/attention.py#L161) , it can be seen that for the `forward` method in `CrossAttention` class, the set of parameters `encode=False, controller_for_inject=None, inject=False, layernum=None, main_height=None, main_width=None` is not used. I think this does not break the code since only the code snippets starting from this [line](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/modules/attention.py#L300) are used since the arguments `encode_uncon == False and decode_uncon == False`  are defaults in the [`apply_model` method](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/ddpm.py#L849). But this leads me to think why these arguments are there. Guessing from its name, it may relate to the set of experiments, for example, Fig 3 and 17, that advocates the usage of DPM solver (with the exceptional prompt) to get the noise-corrupted latent code of the real images (background and foreground). If this is the case, do you mind releasing the code to help me play with different null-text inversion methods, i.e., the methods you compare against in Fig 3?  Initially, I want to test on my own. So I followed your code to use `DPMSolverSampler` to get `z_ref_enc`, but could not find a way to "denoise" it back to the original image because when I set `DPMencode=False`  in the `DPMSolverSampler.sample`, which is expected.

2. I also have questions regarding the code design. I saw in `ldm.models.diffusion.dpm_solver`  folder, you made a significant modification. For example, the [`encode` method ](https://github.com/LuChengTHU/dpm-solver/blob/52bc3fbcd5de56d60917b826b15d2b69460fc2fa/examples/stable-diffusion/ldm/models/diffusion/dpm_solver/sampler.py#L99) of the `DPMSolverSampler` in the original implementation was removed and streamlined in the [`sample` method](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L96). Also, chunks of code are extracted from different places to create "helper functions" like [low_order_sample](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L223). I am wondering are these changes made because of the manipulation of cross-attention map? Or there are some other reasons I am not aware of. 

Thanks,
YD

**Comment by Shilin-LU** [comment]
> Hi, thanks for releasing the code. It's very interesting work. I am new to this topic. Therefore, I have several questions regarding the code that I hope you can help address.
> 
> 1. In the [`attention.py` file](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/modules/attention.py#L161) , it can be seen that for the `forward` method in `CrossAttention` class, the set of parameters `encode=False, controller_for_inject=None, inject=False, layernum=None, main_height=None, main_width=None` is not used. I think this does not break the code since only the code snippets starting from this [line](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/modules/attention.py#L300) are used since the arguments `encode_uncon == False and decode_uncon == False`  are defaults in the [`apply_model` method](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/ddpm.py#L849). But this leads me to think why these arguments are there. Guessing from its name, it may relate to the set of experiments, for example, Fig 3 and 17, that advocates the usage of DPM solver (with the exceptional prompt) to get the noise-corrupted latent code of the real images (background and foreground). If this is the case, do you mind releasing the code to help me play with different null-text inversion methods, i.e., the methods you compare against in Fig 3?  Initially, I want to test on my own. So I followed your code to use `DPMSolverSampler` to get `z_ref_enc`, but could not find a way to "denoise" it back to the original image because when I set `DPMencode=False`  in the `DPMSolverSampler.sample`, which is expected.
> 2. I also have questions regarding the code design. I saw in `ldm.models.diffusion.dpm_solver`  folder, you made a significant modification. For example, the [`encode` method ](https://github.com/LuChengTHU/dpm-solver/blob/52bc3fbcd5de56d60917b826b15d2b69460fc2fa/examples/stable-diffusion/ldm/models/diffusion/dpm_solver/sampler.py#L99) of the `DPMSolverSampler` in the original implementation was removed and streamlined in the [`sample` method](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L96). Also, chunks of code are extracted from different places to create "helper functions" like [low_order_sample](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L223). I am wondering are these changes made because of the manipulation of cross-attention map? Or there are some other reasons I am not aware of.
> 
> Thanks, YD

Hi, thanks for your nice words.

1. Those parameters are used for testing preliminary ideas, and it is completely not used in the finalized version of TF-ICON. Sorry for the confusion caused by the unorganized code. For testing the inversion in Fig. 3, you're right to first get `z_ref_enc` or `z_enc` for the forward process. For the denoising process, we can simply modify the output [here](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L220C22-L220C22) to `return ref['x'].to(device), None` or `return orig['x'].to(device), None`.
3. Yes, these changes just serve for the manipulation of both self-attention maps and cross-attention maps.

**Comment by Yutong-Dai** [comment]
Thanks for your reply. I am able to denoise the latents back to the images. However, I notice that the quality of denoised images varies significantly for the background image (`init_image`) and the foreground image (`ref_image`). The recovered `init_image` is WAY better than `ref_image`, provided that both used 20 denoising steps. An example is provided below.

`init_image`
<img width="1533" alt="image" src="https://github.com/Shilin-LU/TF-ICON/assets/19240875/9f384c2e-d937-4058-b16c-7423789d7643">
`ref_image`
<img width="1508" alt="image" src="https://github.com/Shilin-LU/TF-ICON/assets/19240875/b9855643-6c99-4b36-b1a7-cb44a675342e">

Do you have any idea on the potential cause? I also increased denoising steps to 50, 500, and 1000. However, it does not help improve the quality of `ref_image`.

Denoining `z_ref_enc` with 1000 steps.

<img width="630" alt="image" src="https://github.com/Shilin-LU/TF-ICON/assets/19240875/ddc903a8-cfee-464b-9d9e-d545d8263cb7">


I've provided a MWE below. (You may change the file paths in the `opt` variables)


```python
import os
import PIL
import torch
import numpy as np
from omegaconf import OmegaConf
from PIL import Image
from itertools import islice
from einops import rearrange, repeat
from torch import autocast
from pytorch_lightning import seed_everything
import cv2
import time
from ldm.util import instantiate_from_config
from ldm.models.diffusion.ddim import DDIMSampler
from ldm.models.diffusion.dpm_solver import DPMSolverSampler


def load_model_from_config(config, ckpt, verbose=False):
    print(f"Loading model from {ckpt}")
    pl_sd = torch.load(ckpt, map_location="cpu")
    if "global_step" in pl_sd:
        print(f"Global Step: {pl_sd['global_step']}")
    sd = pl_sd["state_dict"]
    model = instantiate_from_config(config.model)
    m, u = model.load_state_dict(sd, strict=False)
    if len(m) > 0 and verbose:
        print("missing keys:")
        print(m)
    if len(u) > 0 and verbose:
        print("unexpected keys:")
        print(u)

    model.cuda()
    model.eval()
    return model


def chunk(it, size):
    it = iter(it)
    return iter(lambda: tuple(islice(it, size)), ())


def load_img(path, SCALE, pad=False, seg=False, target_size=None):
    if seg:
        # Load the input image and segmentation map
        image = Image.open(path).convert("RGB")
        seg_map = Image.open(seg).convert("1")

        # Get the width and height of the original image
        w, h = image.size

        # Calculate the aspect ratio of the original image
        aspect_ratio = h / w

        # Determine the new dimensions for resizing the image while maintaining aspect ratio
        if aspect_ratio > 1:
            new_w = int(SCALE * 256 / aspect_ratio)
            new_h = int(SCALE * 256)
        else:
            new_w = int(SCALE * 256)
            new_h = int(SCALE * 256 * aspect_ratio)

        # Resize the image and the segmentation map to the new dimensions
        image_resize = image.resize((new_w, new_h))
        segmentation_map_resize = cv2.resize(np.array(seg_map).astype(np.uint8), (new_w, new_h), interpolation=cv2.INTER_NEAREST)

        # Pad the segmentation map to match the target size
        padded_segmentation_map = np.zeros((target_size[1], target_size[0]))
        start_x = (target_size[1] - segmentation_map_resize.shape[0]) // 2
        start_y = (target_size[0] - segmentation_map_resize.shape[1]) // 2
        padded_segmentation_map[start_x: start_x + segmentation_map_resize.shape[0], start_y: start_y + segmentation_map_resize.shape[1]] = segmentation_map_resize

        # Create a new RGB image with the target size and place the resized image in the center
        padded_image = Image.new("RGB", target_size)
        start_x = (target_size[0] - image_resize.width) // 2
        start_y = (target_size[1] - image_resize.height) // 2
        padded_image.paste(image_resize, (start_x, start_y))

        # Update the variable "image" to contain the final padded image
        image = padded_image

    else:
        image = Image.open(path).convert("RGB")
        w, h = image.size        
        print(f"loaded input image of size ({w}, {h}) from {path}")
        w, h = map(lambda x: x - x % 64, (w, h))  # resize to integer multiple of 64
        w = h = 512
        image = image.resize((w, h), resample=PIL.Image.LANCZOS)
        
    image = np.array(image).astype(np.float32) / 255.0
    image = image[None].transpose(0, 3, 1, 2)
    image = torch.from_numpy(image)
    
    if pad or seg:
        return 2. * image - 1., new_w, new_h, padded_segmentation_map
    
    return 2. * image - 1., w, h 


def load_model_and_get_prompt_embedding(model, opt, device, prompts, inv=False):
               
    if inv:
        inv_emb = model.get_learned_conditioning(prompts, inv)
        c = uc = inv_emb
    else:
        inv_emb = None
        
    if opt["scale"] != 1.0:
        uc = model.get_learned_conditioning(opt["n_samples"] * [""])
    else:
        uc = None
    c = model.get_learned_conditioning(prompts)
            
    return c, uc, inv_emb

opt = {
    "cross_domain": False,
    "seed": 3407,
    "ckpt": "./ckpt/v2-1_512-ema-pruned.ckpt",
    "config": "./configs/stable-diffusion/v2-inference.yaml",
    "scale": 2.5,
    "n_samples": 1,
    "f": 16,
    "C": 4,
    "ddim_eta": 0.0,
    "ddim_steps": 20,
    "outdir": "./outputs/",
    "tau_a": 0.4,
    "tau_b": 0.8,
}

config = OmegaConf.load(opt["config"])
model = load_model_from_config(config, opt["ckpt"])    
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model = model.to(device)
sampler = DPMSolverSampler(model)
outpath = opt["outdir"]


prompt = 'an oil painting of a roast Chicken, Van Gogh Style'
opt["init_img"] = f"./inputs/cross_domain/{prompt}/bg61.png"
opt["ref_img"] = f"./inputs/cross_domain/{prompt}/fg37_63d22a7e1f5b66e8e5ac28cc.jpg"
opt["seg"] = f"./inputs/cross_domain/{prompt}/fg37_mask.png"
opt["prompt"] = f"{prompt}"
opt["ddim_steps"] = 20

# the object and background are from different domains
opt["cross_domain"] = True 

if opt["cross_domain"]:
    opt["scale"] = 5.0
    file_name = "cross_domain"
else:
    opt["scale"] = 2.5
    file_name = "same_domain"

ORDER = 2

# indicating the composition location (a replacement method for the user mask); location and size
CENTER_ROW_FROM_TOP = 0.72
CENTER_COL_FROM_LEFT = 0.78
SCALE = 0.65

seed_everything(opt["seed"])
batch_size = opt["n_samples"]
prompt = opt["prompt"]
data = [batch_size * [prompt]]

sample_path = os.path.join(outpath, file_name)
os.makedirs(sample_path, exist_ok=True)
base_count = len(os.listdir(sample_path))
precision_scope = autocast

# read background image
init_image, target_width, target_height = load_img(opt["init_img"], SCALE)
init_image = repeat(init_image.to(device), '1 ... -> b ...', b=batch_size)
save_image = init_image.clone()

# read foreground image and its segmentation map
# pad=True   seg=opt["seg"]
ref_image, width, height, segmentation_map  = load_img(opt["ref_img"], SCALE, seg=opt["seg"], target_size=(target_width, target_height))
ref_image = repeat(ref_image.to(device), '1 ... -> b ...', b=batch_size)


with torch.no_grad():
    with precision_scope("cuda"):
        for prompts in data:
            print(prompts)
            c, uc, inv_emb = load_model_and_get_prompt_embedding(model, opt, device, prompts, inv=True)
            if not opt["cross_domain"]: # same domain
                init_image = save_image
            
            T1 = time.time()
            init_latent = model.get_first_stage_encoding(model.encode_first_stage(init_image))  
            
            # ref's location in ref image in the latent space
            top_rr = int((0.5*(target_height - height))/target_height * init_latent.shape[2])  
            bottom_rr = int((0.5*(target_height + height))/target_height * init_latent.shape[2])  
            left_rr = int((0.5*(target_width - width))/target_width * init_latent.shape[3])  
            right_rr = int((0.5*(target_width + width))/target_width * init_latent.shape[3]) 
                                    
            new_height = bottom_rr - top_rr
            new_width = right_rr - left_rr
            
            step_height2, remainder = divmod(new_height, 2)
            step_height1 = step_height2 + remainder
            step_width2, remainder = divmod(new_width, 2)
            step_width1 = step_width2 + remainder
            
            center_row_rm = int(CENTER_ROW_FROM_TOP * init_latent.shape[2])
            center_col_rm = int(CENTER_COL_FROM_LEFT * init_latent.shape[3])
            
            param = [max(0, int(center_row_rm - step_height1)), 
                    min(init_latent.shape[2] - 1, int(center_row_rm + step_height2)),
                    max(0, int(center_col_rm - step_width1)), 
                    min(init_latent.shape[3] - 1, int(center_col_rm + step_width2))]
            
            ref_latent = model.get_first_stage_encoding(model.encode_first_stage(ref_image))
        
            shape = [init_latent.shape[1], init_latent.shape[2], init_latent.shape[3]]
            z_enc, _ = sampler.sample(steps=opt["ddim_steps"],
                                    inv_emb=inv_emb,
                                    unconditional_conditioning=uc,
                                    conditioning=c,
                                    batch_size=opt["n_samples"],
                                    shape=shape,
                                    verbose=False,
                                    unconditional_guidance_scale=opt["scale"],
                                    eta=opt["ddim_eta"],
                                    order=ORDER,
                                    x_T=init_latent,
                                    width=width,
                                    height=height,
                                    DPMencode=True,
                                    )
            
            z_ref_enc, _ = sampler.sample(steps=opt["ddim_steps"],
                                        inv_emb=inv_emb,
                                        unconditional_conditioning=uc,
                                        conditioning=c,
                                        batch_size=opt["n_samples"],
                                        shape=shape,
                                        verbose=False,
                                        unconditional_guidance_scale=opt["scale"],
                                        eta=opt["ddim_eta"],
                                        order=ORDER,
                                        x_T=ref_latent,
                                        DPMencode=True,
                                        width=width,
                                        height=height,
                                        ref=True,
                                        )

from scripts.dpm_solver_pytorch import NoiseScheduleVP, model_wrapper, DPM_Solver
ns = NoiseScheduleVP('discrete', alphas_cumprod=sampler.alphas_cumprod)
model_fn_decode = model_wrapper(
                lambda x, t, c, DPMencode, controller, inject: sampler.model.apply_model(x, t, c, encode=DPMencode, controller=controller, inject=inject),
                ns,
                model_type='noise',
                guidance_type="classifier-free",
                condition=inv_emb,
                unconditional_condition=inv_emb,
                guidance_scale=opt["scale"],
            )
dpm_solver_decode = DPM_Solver(model_fn_decode, ns)
with autocast('cuda'):
    with torch.no_grad():
        ref, _ = sampler.low_order_sample( z_ref_enc.clone(), dpm_solver_decode, 
                                                        steps=opt["ddim_steps"], 
                                                        order=ORDER, 
                                                        device=sampler.model.betas.device,
                                                        t_start=None, t_end=None, 
                                                        DPMencode=False, controller=None)
        init, _ = sampler.low_order_sample( z_enc.clone(), dpm_solver_decode, 
                                                        steps=opt["ddim_steps"], 
                                                        order=ORDER, 
                                                        device=sampler.model.betas.device,
                                                        t_start=None, t_end=None, 
                                                        DPMencode=False, controller=None)
                
        for step in range(ORDER, opt["ddim_steps"] + 1):               
            ref = dpm_solver_decode.sample_one_step(ref, step, steps=opt["ddim_steps"], order=ORDER, DPMencode=False)
            init = dpm_solver_decode.sample_one_step(init, step, steps=opt["ddim_steps"], order=ORDER, DPMencode=False)
        ref_recover = model.decode_first_stage(ref['x'])
        init_recover = model.decode_first_stage(init['x'])

def tensor_to_pil(tensor_img, mode='RGB'):
    '''
    Convert a 4d tensor image to a PIL image
    '''
    img = tensor_img.squeeze(0).permute(1, 2, 0).cpu().numpy()
    img = (img + 1) / 2 * 255
    img = img.astype(np.uint8)
    return Image.fromarray(img, mode)

# visualize in notebook
tensor_to_pil(ref_recover)
tensor_to_pil(init_recover)
```

**Comment by Shilin-LU** [comment]
I believe the problem of ref images is due to the resizing and padding. If the raw ref image does not go through these pre-processing, this problem will likely be solved.

**Comment by Yutong-Dai** [comment]
Sorry for keeping bothering you. I have some follow-up questions regarding how the cross-attention map A_{l,t}^{cross} in equation (10)  is computed. Upon close inspection, I am looking into the following code chunks.

This [line](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L157C13-L158C123)
```python
cross, cross_controller = self.low_order_sample(x[2], dpm_solver_decode, steps, order, t_start, t_end, device, DPMencode=DPMencode,
                                                                   controller=cross_controller, ref_init=ref['x'].clone())
```
which let me to traced back to this [line](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L234)
```python
 model_prev_list = [dpm_solver.model_fn(x, vec_t, DPMencode=DPMencode, 
                                                   controller=[controller[0][0], controller[1][0], controller[2][0]] if isinstance(controller, list) else controller, 
                                                   inject=inject, ref_init=ref_init)]
```
and further related to these staring from [here](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/dpm_solver.py#L305)
```
        elif guidance_type == "classifier-free":
            if guidance_scale == 1. or unconditional_condition is None:
                return noise_pred_fn(x, t_continuous, cond=condition, DPMencode=DPMencode, controller=controller, inject=inject)
            else:
                if ref_init == None:
                    x_in = torch.cat([x] * 2)
                    c_in = torch.cat([unconditional_condition, condition])
                else:
                    x_in = torch.cat([x, x, ref_init, ref_init], dim=0)
                    uc = torch.cat([unconditional_condition] * 2)
                    c = torch.cat([condition] * 2)
                    c_in = torch.cat([uc, c])
                
                # x_in = torch.cat([x] * 2)
                t_in = torch.cat([t_continuous] * 2)
                
                if ref_init == None:
                    noise_uncond, noise = noise_pred_fn(x_in, t_in, cond=c_in, DPMencode=DPMencode, controller=controller, inject=inject).chunk(2)
                else:
                    noise_uncond, noise, _, _ = noise_pred_fn(x_in, t_in, cond=c_in, DPMencode=DPMencode, controller=controller, inject=inject).chunk(4)
                    
                return noise_uncond + guidance_scale * (noise - noise_uncond)
```
I have following questions.

* It seems that the time step is off by one for the main image latent (`(x[2]`) and reference image latent (`ref['x']`) according to the function call ` self.low_order_sample(x[2], dpm_solver_decode, steps, order, t_start, t_end, device, DPMencode=DPMencode, controller=cross_controller, ref_init=ref['x'].clone())` since `ref['x']` has already been denoised according to this [line](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ldm/models/diffusion/dpm_solver/sampler.py#L152). Could you please comment on this?

* I am confused in the following code chunks.

```python
                if ref_init == None:
                  [omitted]
                else:
                    x_in = torch.cat([x, x, ref_init, ref_init], dim=0)
                    uc = torch.cat([unconditional_condition] * 2)
                    c = torch.cat([condition] * 2)
                    c_in = torch.cat([uc, c])
               [omitted]
                if ref_init == None:
                      [omitted]
                else:
                    noise_uncond, noise, _, _ = noise_pred_fn(x_in, t_in, cond=c_in, DPMencode=DPMencode, controller=controller, inject=inject).chunk(4)
```

Why `x_in` in constructed as `[x, x, ref_init, ref_init]` instead of `[x, ref_init, x, ref_init]`? In the code above, wouldn't the `noise_uncond` and  `noise` be the same thing? [In this context,  `condition`=`unconditional_condition`=`inv_emb`].

* I have one guess is that `noise_uncond + guidance_scale * (noise - noise_uncond)` is useless, i.e, does not have any effect on the final result. Is that right?

* I may also have a guess for the reason to construct  `x_in` as `[x, x, ref_init, ref_init]`. Looking at this [line](https://github.com/Shilin-LU/TF-ICON/blob/324cf786aa12e9ebb4c180990033507fe8422932/ptp_scripts/ptp_utils.py#L229)
```python
 ref_init = rearrange(x[2], '(h w) c ->1 c h w', h=main_height).contiguous()
```
you are extract `ref_init` from the `[x, x, ref_init, ref_init]` from the index 2. Is that right?

If both conjectures are right, can I simply change the code as below to save computation. 

```python
                if ref_init == None:
                  [omitted]
                else:
                    x_in = torch.cat([x, ref_init], dim=0)
                    c_in = torch.cat([unconditional_condition, condition])
               [omitted]
                if ref_init == None:
                      [omitted]
                else:
                    noise_uncond, noise = noise_pred_fn(x_in, t_in, cond=c_in, DPMencode=DPMencode, controller=controller, inject=inject).chunk(2)

# also  change ref_init = rearrange(x[2], '(h w) c ->1 c h w', h=main_height).contiguous() to
 ref_init = rearrange(x[1], '(h w) c ->1 c h w', h=main_height).contiguous()
```

Thanks again for your time.
