### ISSUE TITLE
About custom masks

### ISSUE THREAD

**Issue by sen-mao** [Shilin-LU/TF-ICON#18]
Excellent work: "TF-ICON: Diffusion-Based Training-Free Cross-Domain Image Composition", 
TF-ICON has made significant advancements in terms of training-free image composition, which is truly impressive.

Similar to the examples provided on GitHub, such as **fg_mask.png** and **mask_bg_fg.jpg**, I am keen to understand a convenient method to generate these masks effortlessly for **custom images**. Could you please share insights or suggestions on achieving this?

![绘图](https://github.com/Shilin-LU/TF-ICON/assets/41361872/d944d1a9-db19-4f1f-8362-b809edb6e491)

**Comment by Shilin-LU** [comment]
Hi, thanks for your interest and kind words.

1. For the fg_mask, a good option would be using SAM or [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) to segment your foreground images. 
2. For the mask_bg_fg, we just manually created a binary rectangle image according to the background image such that the size and position of the rectangle for the object composition are reasonable.

**Comment by sen-mao** [comment]
Thank you for your prompt response. 😁
I'll try them.
