### ISSUE TITLE
ask the restriction for mask

### ISSUE THREAD

**Issue by Uchiha-938** [Shilin-LU/TF-ICON#19]
Hello~thank you for your great job, and I have one question: what's the restriction for the mask? I often get<RuntimeError: The size of tensor a must match the size of tensor b at non-singleton dimension 2>when compositing in pixel space. Thank you again!

**Comment by Shilin-LU** [comment]
Thanks for your interest. This issue may arise when the mask is positioned too close to the edge of the image.

**Comment by Uchiha-938** [comment]
Thanks for your response~ I will change the mask.😁

**Comment by Holmes2002** [comment]
@Uchiha-938 Hi so what is my problem
```
   response = f(*args, **kwargs)
  File "scripts/app.py", line 216, in tficon
    = save_image[:, :, center_row_rm - step_height1:center_row_rm + step_height2, center_col_rm - step_width1:center_col_rm + step_width2].clone() \
RuntimeError: The size of tensor a (67) must match the size of tensor b (347) at non-singleton dimension 2
```

![Image](https://github.com/user-attachments/assets/7518bbfe-6cb1-46fc-b434-f0db0bd18188)
