### ISSUE TITLE
Can a 3090 GPU run this code?

### ISSUE THREAD

**Issue by Git-oNmE** [Shilin-LU/TF-ICON#2]
I tried to run this:
```
python scripts/main_tf_icon.py  --ckpt ./ckpt/v2-1_512-ema-pruned.ckpt      \
                                --root ./inputs/same_domain      \
                                --cross_domain False               \
                                --dpm_steps 20                    \
                                --dpm_order 2                     \
                                --scale 5                         \
                                --tau_a 0.4                       \
                                --tau_b 0.8                       \
                                --outdir ./outputs                \
                                --gpu cuda:0                      \
                                --seed 3407 
```

And got the error:
```
RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 23.70 GiB total capacity; 19.30 GiB already allocated; 50.56 MiB free; 22.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Shilin-LU** [comment]
Sorry, seems cannot, the memory requirement is at least greater than 24 GB. Generally, > 25 GB is recommended.

**Comment by Shilin-LU** [comment]
> I tried to run this:
> 
> ```
> python scripts/main_tf_icon.py  --ckpt ./ckpt/v2-1_512-ema-pruned.ckpt      \
>                                 --root ./inputs/same_domain      \
>                                 --cross_domain False               \
>                                 --dpm_steps 20                    \
>                                 --dpm_order 2                     \
>                                 --scale 5                         \
>                                 --tau_a 0.4                       \
>                                 --tau_b 0.8                       \
>                                 --outdir ./outputs                \
>                                 --gpu cuda:0                      \
>                                 --seed 3407 
> ```
> 
> And got the error:
> 
> ```
> RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 23.70 GiB total capacity; 19.30 GiB already allocated; 50.56 MiB free; 22.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```

@eltociear Hi, I've identified a simple way to reduce memory usage in our latest version. One effective solution is to call `torch.cuda.empty_cache()` more frequently, as pointed out in this [section of the code](https://github.com/Shilin-LU/TF-ICON/blob/163cd67fb9605173231210ab16486ee86f269aff/ptp_scripts/ptp_utils.py#L192).

During our evaluation, we observed that the memory consumption was limited to a maximum of 22 GB. Hope this helps!

I encourage you to clone the revised version of our repository (keep the environment the same as ours) and give it another shot.
