### ISSUE TITLE
About Metric Calculations

### ISSUE THREAD

**Issue by SSK-0723** [Shilin-LU/TF-ICON#20]
Thank you for your excellent work, and will the code for calculating the metric in your article be published?

**Comment by Shilin-LU** [comment]
Thank you for your interest. 

To calculate the metrics, you will need to begin by installing two essential libraries: [LPIPS](https://github.com/richzhang/PerceptualSimilarity) and [CLIP](https://github.com/openai/CLIP). For using CLIP to calculate the image similarity, you may refer to their [colab](https://colab.research.google.com/github/openai/clip/blob/master/notebooks/Interacting_with_CLIP.ipynb).

Once these prerequisites are met, the process just involves iterating over two corresponding folders of images to perform the calculation.

**Comment by SSK-0723** [comment]
Thank you for your reply, I have one more question, do you calculate the background and foreground  images separately with the background and reference image when calculating the LPIPS metric?

**Comment by Shilin-LU** [comment]
- When calculating the LPIPS for the background, we mask out the foreground region (according to the user mask) on both the generated composition image and the provided foreground image, i.e., set those pixels to 0. Then calculate the LPIPS on masked images.
- When it comes to the foreground, we crop the generated composition image (according to the user mask), and only compare the foreground image cropped out from the generated image with the provided reference image.

**Comment by SSK-0723** [comment]
Thank you for your quick response.
