### ISSUE TITLE
Tunnel connection failed:403 Forbidden

### ISSUE THREAD

**Issue by szgy66** [Shilin-LU/TF-ICON#21]
Hello, thank you for your work. Now I want to replicate your work on my dataset. When I run the program, I get the following error: 
`(base) root@c5a0a7227fb0:/home/401229/TF-ICON-main# python scripts/main_tf_icon.py  --ckpt ./ckpt/v2-1_512-ema-pruned.ckpt --root ./inputs/cross_domain --domain 'cross' --dpm_steps 20  --dpm_order 2 --scale 5 --tau_a 0.4 --tau_b 0.8 --outdir ./outputs --gpu cuda:0 --seed 3407
Loading model from ./ckpt/v2-1_512-ema-pruned.ckpt
Global Step: 220000
No module 'xformers'. Proceeding without it.
/root/anaconda3/lib/python3.11/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))' thrown while requesting HEAD https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))' thrown while requesting HEAD https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/root/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/root/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 374, in connect
    self._tunnel()
  File "/root/anaconda3/lib/python3.11/http/client.py", line 926, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 403 Forbidden`
Is this because I don't have a VPN? Besides relying on v2-1-512-ema-pruned.ckpt model, will the program download open_clip_pytorch_model.bin? Please help me, thanks!

**Comment by Shilin-LU** [comment]
Sorry, I haven't ever encountered this type of error before. Perhaps you might need a VPN.
