### ISSUE TITLE
About Metric Calculations 

### ISSUE THREAD

**Issue by sherlhw** [Shilin-LU/TF-ICON#25]
May I ask what is the ground truth for cross-domain image synthesis when calculating quantitative indicators?Is 'cp_bg_fg.jpg'?

**Comment by Shilin-LU** [comment]
Not using 'cp_bg_fg.jpg'.

When calculating metrics for the background, the original background image with the foreground region masked out is used. 

When calculating metrics for the foreground, the original foreground image and the generated foreground cropped out from the composition image are used.

**Comment by sherlhw** [comment]
For cross-style synthesis, the style of the original foreground image and the style of the generated foreground are inconsistent.Is this ground truth appropriate？

**Comment by Shilin-LU** [comment]
Oh, sorry I thought you were asking about the same-style generation. 

For the cross-style one, we didn't do the quantitative evaluation in our paper. Instead, we conducted a user study for it

**Comment by sherlhw** [comment]
I see. Thank you very much for your reply.
