### ISSUE TITLE
About composition on x-ray dataset

### ISSUE THREAD

**Issue by pILLOW-1** [Shilin-LU/TF-ICON#26]
Hi, great work!
It is known that there is a gap between x-ray and natural image domains. I wonder if TF-ICON can do image composition on x-ray image datasets. Thanks a lot!

**Comment by Shilin-LU** [comment]
Thank you for your interest!

TF-ICON is a training-free method, and its capabilities are limited by the pretrained model it relies on. We developed it using Stable Diffusion, which is designed to handle only natural or real images. Therefore, TF-ICON is not suitable for processing X-ray images.

**Comment by pILLOW-1** [comment]
Got it. Thank you!
