### ISSUE TITLE
Request a PPT version of the model pipeline diagram

### ISSUE THREAD

**Issue by sherlhw** [Shilin-LU/TF-ICON#29]
Thank you very much for your work, which is very meaningful. I want to use your model as an example in my graduation thesis. Is it OK to have a PPT or svg format model pipeline diagram?

**Comment by Shilin-LU** [comment]
Thank you for your kind words. This is the [SVG](https://github.com/user-attachments/assets/ea1e0c2b-d33a-4157-a16d-20d375c09646) of the pipeline. If you find it helpful, please consider giving our repository a star.

**Comment by sherlhw** [comment]
Thank you very much, already star!
