### ISSUE TITLE
Gradio APP build invitation

### ISSUE THREAD

**Issue by ZhaoQiiii** [Shilin-LU/TF-ICON#3]
Hi, thank you very much for your open source work! I am an employee of the Shanghai Artificial Intelligence Lab. I would like to invite you to build the Gradio Demo of TF-ICON on our [OpenXLab](https://openxlab.org.cn/apps). We can provide you with GPU inference and operation support for free. Looking forward to your reply!

**Comment by Shilin-LU** [comment]
Thank you for reaching out, and I appreciate your invitation to build the Gradio Demo on OpenXLab. I'd be happy to discuss this further with you! You can reach me via email.
