### ISSUE TITLE
Query regarding setting batch size

### ISSUE THREAD

**Issue by 1siddhi7** [Shilin-LU/TF-ICON#7]
Hi! I couldn't find in the codebase if setting `n_samples = 8` would automatically walk through a folder with 8 background and 8 foreground images while using the same prompt. The `init_image` and `ref_image` seem to be resized using the `repeat()` function.  Would it be possible to please show an example using n_samples argument?

Also, thanks for open-sourcing this wonderful work!

**Comment by Shilin-LU** [comment]
Hi, Thank you for your positive feedback!

Unfortunately, the **n_samples** parameter is not currently supported in our codebase (it is used in the original stable diffusion codebase). However, I understand that you are looking to *process a batch of images with different background and foreground combinations using the same prompt*. Here is a streamlined approach to achieve this:

### Step 1: Organize Your Files
You can organize your images into separate folders. You can have 8 folders, each containing a unique combination of one background and one foreground image. Name these folders with order numbers and the common prompt. For instance:

```python
./inputs/same_domain/01_a_professional_photograph_of_a_tart_and_spring_rolls_ultra_realistic/
./inputs/same_domain/02_a_professional_photograph_of_a_tart_and_spring_rolls_ultra_realistic/
./inputs/same_domain/03_a_professional_photograph_of_a_tart_and_spring_rolls_ultra_realistic/
```

### Step 2: Modify the Script
You will need to modify the script to process these folders correctly. Navigate to [line 302](https://github.com/Shilin-LU/TF-ICON/blob/899d800090e8e2893d98ec44bb2dc4be95dfb332/scripts/main_tf_icon.py#L302) in **scripts/main_tf_icon.py** and update it to:

```python
result = re.search(r'./inputs/[^/]+/\d{2}_([^/]+)/bg\d+\.', file_path)
```
This can extract the prompt without order numbers. With your files organized and script modified, you should now be able to run your script and process the image combinations using the same prompt.

I hope this helps!

**Comment by 1siddhi7** [comment]
Hi! This helps, thanks!
